---
title: "assignment presentation"
author: "Han Xiao,jerry Ma, tianlang Yang"
date: "2/14/2018"
output: 
  slidy_presentation:
    css: scroll.css
    incremental: true
runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## data clean
```{r}

data2010<-read.csv("bp appre 2010.csv")
data2010
data2017<-read.csv("bp appre 2017.csv")
datas<-read.csv("PB monthly summaries.csv")
datas2 = apply(t(datas[,2:13]),1,rev) 
#datas <- rev(datas)
datas$mean<-apply(datas[,2:13],1,mean)
ndata<-nrow(datas[,2:13])
rownames(datas)<-datas[,1]
datas<-cbind(datas,rowSums(datas))
colnames(datas)<-c(colnames(datas)[-length(colnames(datas))],"Total")
datas<-subset(datas,select=-c(year))
#View(datas)
rownames(data2010)<-data2010[,1]
data2010<-subset(data2010,select=-c(Sector))
rownames(data2017)<-data2017[,1]
data2017<-subset(data2017,select=-c(Sector))
data2010 <- rbind(data2010, colSums(data2010))

#rownames(data2010)
  
rownames(data2010) <- c(rownames(data2010)[-length(rownames(data2010))], "Total")

data2010 <- cbind(data2010,rowSums(data2010))

colnames(data2010) <- c(colnames(data2010)[-length(colnames(data2010))], "Total")

#View(data2010)

data2017 <- rbind(data2017, colSums(data2010))
  
rownames(data2017) <- c(rownames(data2017)[-length(rownames(data2017))], "Total")

data2017 <- cbind(data2017,rowSums(data2017))

colnames(data2017) <- c(colnames(data2017)[-length(colnames(data2017))], "Total")
```

##Statistic data ttest
```{r}
mean2010s<-apply(data2010[,1:12],1,mean)
mean2010m<-apply(data2010[,1:12],2,mean)
mean2017s<-apply(data2017[,1:12],1,mean)
mean2017m<-apply(data2017[,1:12],2,mean)
bpsector<-cbind(mean2010s,mean2017s)
bpmonth<-cbind(mean2010m,mean2017m)
sec2010<-as.data.frame(t(data2010[,1:12]))
as.character(colnames(sec2010))
sec2017<-as.data.frame(t(data2017[,1:12]))
as.character(colnames(sec2017))
t.test(sec2010$Tucson,sec2017$`Rio Grande Valley`)
month2010<-as.data.frame((data2010[,6:8]))
as.character(rownames(month2010))
month2010$sum<-apply(month2010,1,sum)
maxmonth2010<-max(month2010$sum)
month2017<-as.data.frame((data2017[,1:3]))
as.character(rownames(month2017))
month2017$sum<-apply(month2017,1,sum)
maxmonth2017<-max(month2017$sum)
t.test(month2010$sum,month2017$sum)
```


##Barplots
> - 2017 visualization
```{r}
barplot(data2017[1:9,13], names.arg = rownames(data2017)[1:9], 
        las=2,
        axisnames=TRUE,
        main="2017 Border Patrol Apprehensions by Sector",
        border="blue",
        col="red")

```



> -2010 visualization
```{r}
barplot(data2010[1:9,13], names.arg = rownames(data2010)[1:9], 
        las=2,
        axisnames=TRUE,
        main="2010 Border Patrol Apprehensions by Sector",
        border="blue",
        col="yellow")
```

> -comparison
```{r}
barplot(t(bpsector),beside = TRUE,legend.text = c("2010","2017"),main = "compare by sector")
barplot(t(bpmonth),beside = TRUE,legend.text = c("2010","2017"),main = "compare by month")
```


##time series
```{r}
ts2 <- as.vector(t(datas2))
ts3 <- ts(ts2,frequency = 13,start = c(2000,10))
ts.plot(ts3,gpars = list(xlab="year",ylab="appre"))
datasmean <- apply(datas2,1,mean)

points(c(2001:2018), datasmean, pch = 19, col = 'red')
text(c(2001:2018), datasmean, c(2000:2017))
```
